BasedOnStyle: LLVM
BreakBeforeBraces: Custom
BraceWrapping:
  AfterFunction:         false
  AfterControlStatement: false
  AfterClass:            false
  AfterEnum:             false
  AfterNamespace:        false
  AfterUnion:            false
  BeforeElse:            false
  BeforeCatch:           false
  SplitEmptyFunction:    false
  SplitEmptyRecord:      false
  SplitEmptyNamespace:   false
IndentWidth: 2
ColumnLimit: 0
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
AllowShortBlocksOnASingleLine: Never
SpaceBeforeParens: ControlStatements
PointerAlignment: Left
