[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino

monitor_speed = 115200

; upload_protocol = espota ; Caso use OTA
; upload_port = esp32name.local

build_src_filter = +<main4.cpp>
